
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20160615 (GIT 4ac7450)
//----------------------------------------------------

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int MENOR = 16;
  public static final int IDENT = 29;
  public static final int PUNTOYCOMA = 26;
  public static final int IGUAL = 11;
  public static final int MENORIGUAL = 13;
  public static final int SUMA = 18;
  public static final int LEER = 8;
  public static final int PARIZQ = 22;
  public static final int IMPRIMIR = 9;
  public static final int PARDER = 23;
  public static final int LLAVEIZQ = 24;
  public static final int COMA = 27;
  public static final int INTERCAMBIAR = 10;
  public static final int LLAVEDER = 25;
  public static final int MULT = 20;
  public static final int MAYOR = 17;
  public static final int EOF = 0;
  public static final int DIFERENTE = 12;
  public static final int SINO = 6;
  public static final int DIV = 21;
  public static final int MAYORIGUAL = 14;
  public static final int SI = 5;
  public static final int NUMERO = 28;
  public static final int error = 1;
  public static final int ENTERO = 4;
  public static final int MIENTRAS = 7;
  public static final int FIN = 3;
  public static final int ASIG = 15;
  public static final int RESTA = 19;
  public static final int INICIO = 2;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "INICIO",
  "FIN",
  "ENTERO",
  "SI",
  "SINO",
  "MIENTRAS",
  "LEER",
  "IMPRIMIR",
  "INTERCAMBIAR",
  "IGUAL",
  "DIFERENTE",
  "MENORIGUAL",
  "MAYORIGUAL",
  "ASIG",
  "MENOR",
  "MAYOR",
  "SUMA",
  "RESTA",
  "MULT",
  "DIV",
  "PARIZQ",
  "PARDER",
  "LLAVEIZQ",
  "LLAVEDER",
  "PUNTOYCOMA",
  "COMA",
  "NUMERO",
  "IDENT"
  };
}

